// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: controlplane/v1/controlplane.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Health_FullMethodName              = "/swarmos.controlplane.v1.ControlPlane/Health"
	ControlPlane_CreateSwarm_FullMethodName         = "/swarmos.controlplane.v1.ControlPlane/CreateSwarm"
	ControlPlane_GetSwarm_FullMethodName            = "/swarmos.controlplane.v1.ControlPlane/GetSwarm"
	ControlPlane_ListSwarms_FullMethodName          = "/swarmos.controlplane.v1.ControlPlane/ListSwarms"
	ControlPlane_CreateAgentTemplate_FullMethodName = "/swarmos.controlplane.v1.ControlPlane/CreateAgentTemplate"
	ControlPlane_ListAgentTemplates_FullMethodName  = "/swarmos.controlplane.v1.ControlPlane/ListAgentTemplates"
	ControlPlane_RegisterAgent_FullMethodName       = "/swarmos.controlplane.v1.ControlPlane/RegisterAgent"
	ControlPlane_ListAgents_FullMethodName          = "/swarmos.controlplane.v1.ControlPlane/ListAgents"
	ControlPlane_CreateTask_FullMethodName          = "/swarmos.controlplane.v1.ControlPlane/CreateTask"
	ControlPlane_GetTask_FullMethodName             = "/swarmos.controlplane.v1.ControlPlane/GetTask"
	ControlPlane_ListTasks_FullMethodName           = "/swarmos.controlplane.v1.ControlPlane/ListTasks"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane 是 SwarmOS 的外部资源 API。
// HTTP 与 gRPC 使用同一套消息，避免两套接口在字段和状态语义上漂移。
type ControlPlaneClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error)
	CreateSwarm(ctx context.Context, in *CreateSwarmRequest, opts ...grpc.CallOption) (*Swarm, error)
	GetSwarm(ctx context.Context, in *GetSwarmRequest, opts ...grpc.CallOption) (*Swarm, error)
	ListSwarms(ctx context.Context, in *ListSwarmsRequest, opts ...grpc.CallOption) (*ListSwarmsReply, error)
	CreateAgentTemplate(ctx context.Context, in *CreateAgentTemplateRequest, opts ...grpc.CallOption) (*AgentTemplate, error)
	ListAgentTemplates(ctx context.Context, in *ListAgentTemplatesRequest, opts ...grpc.CallOption) (*ListAgentTemplatesReply, error)
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentInstance, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, ControlPlane_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateSwarm(ctx context.Context, in *CreateSwarmRequest, opts ...grpc.CallOption) (*Swarm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Swarm)
	err := c.cc.Invoke(ctx, ControlPlane_CreateSwarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetSwarm(ctx context.Context, in *GetSwarmRequest, opts ...grpc.CallOption) (*Swarm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Swarm)
	err := c.cc.Invoke(ctx, ControlPlane_GetSwarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListSwarms(ctx context.Context, in *ListSwarmsRequest, opts ...grpc.CallOption) (*ListSwarmsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSwarmsReply)
	err := c.cc.Invoke(ctx, ControlPlane_ListSwarms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateAgentTemplate(ctx context.Context, in *CreateAgentTemplateRequest, opts ...grpc.CallOption) (*AgentTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTemplate)
	err := c.cc.Invoke(ctx, ControlPlane_CreateAgentTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListAgentTemplates(ctx context.Context, in *ListAgentTemplatesRequest, opts ...grpc.CallOption) (*ListAgentTemplatesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentTemplatesReply)
	err := c.cc.Invoke(ctx, ControlPlane_ListAgentTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInstance)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsReply)
	err := c.cc.Invoke(ctx, ControlPlane_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ControlPlane_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ControlPlane_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksReply)
	err := c.cc.Invoke(ctx, ControlPlane_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane 是 SwarmOS 的外部资源 API。
// HTTP 与 gRPC 使用同一套消息，避免两套接口在字段和状态语义上漂移。
type ControlPlaneServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthReply, error)
	CreateSwarm(context.Context, *CreateSwarmRequest) (*Swarm, error)
	GetSwarm(context.Context, *GetSwarmRequest) (*Swarm, error)
	ListSwarms(context.Context, *ListSwarmsRequest) (*ListSwarmsReply, error)
	CreateAgentTemplate(context.Context, *CreateAgentTemplateRequest) (*AgentTemplate, error)
	ListAgentTemplates(context.Context, *ListAgentTemplatesRequest) (*ListAgentTemplatesReply, error)
	RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentInstance, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error)
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Health(context.Context, *emptypb.Empty) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedControlPlaneServer) CreateSwarm(context.Context, *CreateSwarmRequest) (*Swarm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSwarm not implemented")
}
func (UnimplementedControlPlaneServer) GetSwarm(context.Context, *GetSwarmRequest) (*Swarm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwarm not implemented")
}
func (UnimplementedControlPlaneServer) ListSwarms(context.Context, *ListSwarmsRequest) (*ListSwarmsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSwarms not implemented")
}
func (UnimplementedControlPlaneServer) CreateAgentTemplate(context.Context, *CreateAgentTemplateRequest) (*AgentTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentTemplate not implemented")
}
func (UnimplementedControlPlaneServer) ListAgentTemplates(context.Context, *ListAgentTemplatesRequest) (*ListAgentTemplatesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentTemplates not implemented")
}
func (UnimplementedControlPlaneServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedControlPlaneServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedControlPlaneServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedControlPlaneServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedControlPlaneServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateSwarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateSwarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateSwarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateSwarm(ctx, req.(*CreateSwarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetSwarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetSwarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetSwarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetSwarm(ctx, req.(*GetSwarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListSwarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSwarmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListSwarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListSwarms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListSwarms(ctx, req.(*ListSwarmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateAgentTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateAgentTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateAgentTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateAgentTemplate(ctx, req.(*CreateAgentTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListAgentTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListAgentTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListAgentTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListAgentTemplates(ctx, req.(*ListAgentTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarmos.controlplane.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ControlPlane_Health_Handler,
		},
		{
			MethodName: "CreateSwarm",
			Handler:    _ControlPlane_CreateSwarm_Handler,
		},
		{
			MethodName: "GetSwarm",
			Handler:    _ControlPlane_GetSwarm_Handler,
		},
		{
			MethodName: "ListSwarms",
			Handler:    _ControlPlane_ListSwarms_Handler,
		},
		{
			MethodName: "CreateAgentTemplate",
			Handler:    _ControlPlane_CreateAgentTemplate_Handler,
		},
		{
			MethodName: "ListAgentTemplates",
			Handler:    _ControlPlane_ListAgentTemplates_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _ControlPlane_RegisterAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _ControlPlane_ListAgents_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _ControlPlane_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ControlPlane_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ControlPlane_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/v1/controlplane.proto",
}
