// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: controlplane/v1/controlplane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *HealthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type Swarm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Goal             string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BudgetTokens     int64                  `protobuf:"varint,5,opt,name=budget_tokens,json=budgetTokens,proto3" json:"budget_tokens,omitempty"`
	BudgetCostMicros int64                  `protobuf:"varint,6,opt,name=budget_cost_micros,json=budgetCostMicros,proto3" json:"budget_cost_micros,omitempty"`
	MaxAgents        int32                  `protobuf:"varint,7,opt,name=max_agents,json=maxAgents,proto3" json:"max_agents,omitempty"`
	Policy           *structpb.Struct       `protobuf:"bytes,8,opt,name=policy,proto3" json:"policy,omitempty"`
	Version          int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Swarm) Reset() {
	*x = Swarm{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swarm) ProtoMessage() {}

func (x *Swarm) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swarm.ProtoReflect.Descriptor instead.
func (*Swarm) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *Swarm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Swarm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Swarm) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Swarm) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Swarm) GetBudgetTokens() int64 {
	if x != nil {
		return x.BudgetTokens
	}
	return 0
}

func (x *Swarm) GetBudgetCostMicros() int64 {
	if x != nil {
		return x.BudgetCostMicros
	}
	return 0
}

func (x *Swarm) GetMaxAgents() int32 {
	if x != nil {
		return x.MaxAgents
	}
	return 0
}

func (x *Swarm) GetPolicy() *structpb.Struct {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Swarm) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Swarm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Swarm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSwarmRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Goal             string                 `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`
	BudgetTokens     int64                  `protobuf:"varint,3,opt,name=budget_tokens,json=budgetTokens,proto3" json:"budget_tokens,omitempty"`
	BudgetCostMicros int64                  `protobuf:"varint,4,opt,name=budget_cost_micros,json=budgetCostMicros,proto3" json:"budget_cost_micros,omitempty"`
	MaxAgents        int32                  `protobuf:"varint,5,opt,name=max_agents,json=maxAgents,proto3" json:"max_agents,omitempty"`
	Policy           *structpb.Struct       `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSwarmRequest) Reset() {
	*x = CreateSwarmRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSwarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSwarmRequest) ProtoMessage() {}

func (x *CreateSwarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSwarmRequest.ProtoReflect.Descriptor instead.
func (*CreateSwarmRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSwarmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSwarmRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateSwarmRequest) GetBudgetTokens() int64 {
	if x != nil {
		return x.BudgetTokens
	}
	return 0
}

func (x *CreateSwarmRequest) GetBudgetCostMicros() int64 {
	if x != nil {
		return x.BudgetCostMicros
	}
	return 0
}

func (x *CreateSwarmRequest) GetMaxAgents() int32 {
	if x != nil {
		return x.MaxAgents
	}
	return 0
}

func (x *CreateSwarmRequest) GetPolicy() *structpb.Struct {
	if x != nil {
		return x.Policy
	}
	return nil
}

type GetSwarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwarmRequest) Reset() {
	*x = GetSwarmRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwarmRequest) ProtoMessage() {}

func (x *GetSwarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwarmRequest.ProtoReflect.Descriptor instead.
func (*GetSwarmRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *GetSwarmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSwarmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSwarmsRequest) Reset() {
	*x = ListSwarmsRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSwarmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwarmsRequest) ProtoMessage() {}

func (x *ListSwarmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwarmsRequest.ProtoReflect.Descriptor instead.
func (*ListSwarmsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *ListSwarmsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSwarmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Swarm               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSwarmsReply) Reset() {
	*x = ListSwarmsReply{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSwarmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSwarmsReply) ProtoMessage() {}

func (x *ListSwarmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSwarmsReply.ProtoReflect.Descriptor instead.
func (*ListSwarmsReply) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *ListSwarmsReply) GetItems() []*Swarm {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSwarmsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AgentTemplate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role            string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model           string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Skills          map[string]float64     `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Tools           []string               `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	Permissions     []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TemplateVersion string                 `protobuf:"bytes,9,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	Enabled         bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentTemplate) Reset() {
	*x = AgentTemplate{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTemplate) ProtoMessage() {}

func (x *AgentTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTemplate.ProtoReflect.Descriptor instead.
func (*AgentTemplate) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *AgentTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentTemplate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentTemplate) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AgentTemplate) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentTemplate) GetSkills() map[string]float64 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentTemplate) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentTemplate) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AgentTemplate) GetTemplateVersion() string {
	if x != nil {
		return x.TemplateVersion
	}
	return ""
}

func (x *AgentTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAgentTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Prompt          string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Skills          map[string]float64     `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Tools           []string               `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	Permissions     []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TemplateVersion string                 `protobuf:"bytes,8,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAgentTemplateRequest) Reset() {
	*x = CreateAgentTemplateRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentTemplateRequest) ProtoMessage() {}

func (x *CreateAgentTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentTemplateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAgentTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentTemplateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateAgentTemplateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateAgentTemplateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateAgentTemplateRequest) GetSkills() map[string]float64 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateAgentTemplateRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CreateAgentTemplateRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateAgentTemplateRequest) GetTemplateVersion() string {
	if x != nil {
		return x.TemplateVersion
	}
	return ""
}

type ListAgentTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentTemplatesRequest) Reset() {
	*x = ListAgentTemplatesRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentTemplatesRequest) ProtoMessage() {}

func (x *ListAgentTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *ListAgentTemplatesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAgentTemplatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AgentTemplate       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentTemplatesReply) Reset() {
	*x = ListAgentTemplatesReply{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentTemplatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentTemplatesReply) ProtoMessage() {}

func (x *ListAgentTemplatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentTemplatesReply.ProtoReflect.Descriptor instead.
func (*ListAgentTemplatesReply) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *ListAgentTemplatesReply) GetItems() []*AgentTemplate {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAgentTemplatesReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AgentInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SwarmId       string                 `protobuf:"bytes,3,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Load          float64                `protobuf:"fixed64,6,opt,name=load,proto3" json:"load,omitempty"`
	HeartbeatAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=heartbeat_at,json=heartbeatAt,proto3" json:"heartbeat_at,omitempty"`
	Version       int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInstance) Reset() {
	*x = AgentInstance{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstance) ProtoMessage() {}

func (x *AgentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstance.ProtoReflect.Descriptor instead.
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *AgentInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInstance) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *AgentInstance) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *AgentInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInstance) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *AgentInstance) GetHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatAt
	}
	return nil
}

func (x *AgentInstance) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AgentInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentInstance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SwarmId       string                 `protobuf:"bytes,2,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterAgentRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *RegisterAgentRequest) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwarmId       string                 `protobuf:"bytes,1,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *ListAgentsRequest) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *ListAgentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAgentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AgentInstance       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsReply) Reset() {
	*x = ListAgentsReply{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsReply) ProtoMessage() {}

func (x *ListAgentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsReply.ProtoReflect.Descriptor instead.
func (*ListAgentsReply) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *ListAgentsReply) GetItems() []*AgentInstance {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAgentsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SwarmId         string                 `protobuf:"bytes,2,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	ParentId        string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Goal            string                 `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Priority        int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Input           *structpb.Struct       `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	Requirements    *structpb.Struct       `protobuf:"bytes,9,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Acceptance      *structpb.Struct       `protobuf:"bytes,10,opt,name=acceptance,proto3" json:"acceptance,omitempty"`
	ExecutionPolicy *structpb.Struct       `protobuf:"bytes,11,opt,name=execution_policy,json=executionPolicy,proto3" json:"execution_policy,omitempty"`
	DependencyIds   []string               `protobuf:"bytes,12,rep,name=dependency_ids,json=dependencyIds,proto3" json:"dependency_ids,omitempty"`
	AssignedAgentId string                 `protobuf:"bytes,13,opt,name=assigned_agent_id,json=assignedAgentId,proto3" json:"assigned_agent_id,omitempty"`
	AttemptCount    int32                  `protobuf:"varint,14,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	Version         int64                  `protobuf:"varint,15,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *Task) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Task) GetAcceptance() *structpb.Struct {
	if x != nil {
		return x.Acceptance
	}
	return nil
}

func (x *Task) GetExecutionPolicy() *structpb.Struct {
	if x != nil {
		return x.ExecutionPolicy
	}
	return nil
}

func (x *Task) GetDependencyIds() []string {
	if x != nil {
		return x.DependencyIds
	}
	return nil
}

func (x *Task) GetAssignedAgentId() string {
	if x != nil {
		return x.AssignedAgentId
	}
	return ""
}

func (x *Task) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *Task) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SwarmId         string                 `protobuf:"bytes,1,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	ParentId        string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Goal            string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Input           *structpb.Struct       `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	Requirements    *structpb.Struct       `protobuf:"bytes,7,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Acceptance      *structpb.Struct       `protobuf:"bytes,8,opt,name=acceptance,proto3" json:"acceptance,omitempty"`
	ExecutionPolicy *structpb.Struct       `protobuf:"bytes,9,opt,name=execution_policy,json=executionPolicy,proto3" json:"execution_policy,omitempty"`
	DependencyIds   []string               `protobuf:"bytes,10,rep,name=dependency_ids,json=dependencyIds,proto3" json:"dependency_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTaskRequest) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *CreateTaskRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateTaskRequest) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CreateTaskRequest) GetAcceptance() *structpb.Struct {
	if x != nil {
		return x.Acceptance
	}
	return nil
}

func (x *CreateTaskRequest) GetExecutionPolicy() *structpb.Struct {
	if x != nil {
		return x.ExecutionPolicy
	}
	return nil
}

func (x *CreateTaskRequest) GetDependencyIds() []string {
	if x != nil {
		return x.DependencyIds
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{17}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwarmId       string                 `protobuf:"bytes,1,opt,name=swarm_id,json=swarmId,proto3" json:"swarm_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *ListTasksRequest) GetSwarmId() string {
	if x != nil {
		return x.SwarmId
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Task                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReply) Reset() {
	*x = ListTasksReply{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReply) ProtoMessage() {}

func (x *ListTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReply.ProtoReflect.Descriptor instead.
func (*ListTasksReply) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{19}
}

func (x *ListTasksReply) GetItems() []*Task {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTasksReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\"controlplane/v1/controlplane.proto\x12\x17swarmos.controlplane.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\vHealthReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8a\x03\n" +
	"\x05Swarm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rbudget_tokens\x18\x05 \x01(\x03R\fbudgetTokens\x12,\n" +
	"\x12budget_cost_micros\x18\x06 \x01(\x03R\x10budgetCostMicros\x12\x1d\n" +
	"\n" +
	"max_agents\x18\a \x01(\x05R\tmaxAgents\x12/\n" +
	"\x06policy\x18\b \x01(\v2\x17.google.protobuf.StructR\x06policy\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdf\x01\n" +
	"\x12CreateSwarmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x02 \x01(\tR\x04goal\x12#\n" +
	"\rbudget_tokens\x18\x03 \x01(\x03R\fbudgetTokens\x12,\n" +
	"\x12budget_cost_micros\x18\x04 \x01(\x03R\x10budgetCostMicros\x12\x1d\n" +
	"\n" +
	"max_agents\x18\x05 \x01(\x05R\tmaxAgents\x12/\n" +
	"\x06policy\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06policy\"!\n" +
	"\x0fGetSwarmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x11ListSwarmsRequest\x128\n" +
	"\x04page\x18\x01 \x01(\v2$.swarmos.controlplane.v1.PageRequestR\x04page\"o\n" +
	"\x0fListSwarmsReply\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.swarmos.controlplane.v1.SwarmR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xef\x03\n" +
	"\rAgentTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12J\n" +
	"\x06skills\x18\x06 \x03(\v22.swarmos.controlplane.v1.AgentTemplate.SkillsEntryR\x06skills\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\x12)\n" +
	"\x10template_version\x18\t \x01(\tR\x0ftemplateVersion\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe9\x02\n" +
	"\x1aCreateAgentTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12W\n" +
	"\x06skills\x18\x05 \x03(\v2?.swarmos.controlplane.v1.CreateAgentTemplateRequest.SkillsEntryR\x06skills\x12\x14\n" +
	"\x05tools\x18\x06 \x03(\tR\x05tools\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12)\n" +
	"\x10template_version\x18\b \x01(\tR\x0ftemplateVersion\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"U\n" +
	"\x19ListAgentTemplatesRequest\x128\n" +
	"\x04page\x18\x01 \x01(\v2$.swarmos.controlplane.v1.PageRequestR\x04page\"\x7f\n" +
	"\x17ListAgentTemplatesReply\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.swarmos.controlplane.v1.AgentTemplateR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xea\x02\n" +
	"\rAgentInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bswarm_id\x18\x03 \x01(\tR\aswarmId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04load\x18\x06 \x01(\x01R\x04load\x12=\n" +
	"\fheartbeat_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vheartbeatAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"f\n" +
	"\x14RegisterAgentRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bswarm_id\x18\x02 \x01(\tR\aswarmId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"h\n" +
	"\x11ListAgentsRequest\x12\x19\n" +
	"\bswarm_id\x18\x01 \x01(\tR\aswarmId\x128\n" +
	"\x04page\x18\x02 \x01(\v2$.swarmos.controlplane.v1.PageRequestR\x04page\"w\n" +
	"\x0fListAgentsReply\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.swarmos.controlplane.v1.AgentInstanceR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9b\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bswarm_id\x18\x02 \x01(\tR\aswarmId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x05 \x01(\tR\x04goal\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12-\n" +
	"\x05input\x18\b \x01(\v2\x17.google.protobuf.StructR\x05input\x12;\n" +
	"\frequirements\x18\t \x01(\v2\x17.google.protobuf.StructR\frequirements\x127\n" +
	"\n" +
	"acceptance\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\n" +
	"acceptance\x12B\n" +
	"\x10execution_policy\x18\v \x01(\v2\x17.google.protobuf.StructR\x0fexecutionPolicy\x12%\n" +
	"\x0edependency_ids\x18\f \x03(\tR\rdependencyIds\x12*\n" +
	"\x11assigned_agent_id\x18\r \x01(\tR\x0fassignedAgentId\x12#\n" +
	"\rattempt_count\x18\x0e \x01(\x05R\fattemptCount\x12\x18\n" +
	"\aversion\x18\x0f \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x03\n" +
	"\x11CreateTaskRequest\x12\x19\n" +
	"\bswarm_id\x18\x01 \x01(\tR\aswarmId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12-\n" +
	"\x05input\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05input\x12;\n" +
	"\frequirements\x18\a \x01(\v2\x17.google.protobuf.StructR\frequirements\x127\n" +
	"\n" +
	"acceptance\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"acceptance\x12B\n" +
	"\x10execution_policy\x18\t \x01(\v2\x17.google.protobuf.StructR\x0fexecutionPolicy\x12%\n" +
	"\x0edependency_ids\x18\n" +
	" \x03(\tR\rdependencyIds\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x7f\n" +
	"\x10ListTasksRequest\x12\x19\n" +
	"\bswarm_id\x18\x01 \x01(\tR\aswarmId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x128\n" +
	"\x04page\x18\x03 \x01(\v2$.swarmos.controlplane.v1.PageRequestR\x04page\"m\n" +
	"\x0eListTasksReply\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.swarmos.controlplane.v1.TaskR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xb5\b\n" +
	"\fControlPlane\x12F\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a$.swarmos.controlplane.v1.HealthReply\x12Z\n" +
	"\vCreateSwarm\x12+.swarmos.controlplane.v1.CreateSwarmRequest\x1a\x1e.swarmos.controlplane.v1.Swarm\x12T\n" +
	"\bGetSwarm\x12(.swarmos.controlplane.v1.GetSwarmRequest\x1a\x1e.swarmos.controlplane.v1.Swarm\x12b\n" +
	"\n" +
	"ListSwarms\x12*.swarmos.controlplane.v1.ListSwarmsRequest\x1a(.swarmos.controlplane.v1.ListSwarmsReply\x12r\n" +
	"\x13CreateAgentTemplate\x123.swarmos.controlplane.v1.CreateAgentTemplateRequest\x1a&.swarmos.controlplane.v1.AgentTemplate\x12z\n" +
	"\x12ListAgentTemplates\x122.swarmos.controlplane.v1.ListAgentTemplatesRequest\x1a0.swarmos.controlplane.v1.ListAgentTemplatesReply\x12f\n" +
	"\rRegisterAgent\x12-.swarmos.controlplane.v1.RegisterAgentRequest\x1a&.swarmos.controlplane.v1.AgentInstance\x12b\n" +
	"\n" +
	"ListAgents\x12*.swarmos.controlplane.v1.ListAgentsRequest\x1a(.swarmos.controlplane.v1.ListAgentsReply\x12W\n" +
	"\n" +
	"CreateTask\x12*.swarmos.controlplane.v1.CreateTaskRequest\x1a\x1d.swarmos.controlplane.v1.Task\x12Q\n" +
	"\aGetTask\x12'.swarmos.controlplane.v1.GetTaskRequest\x1a\x1d.swarmos.controlplane.v1.Task\x12_\n" +
	"\tListTasks\x12).swarmos.controlplane.v1.ListTasksRequest\x1a'.swarmos.controlplane.v1.ListTasksReplyB4Z2github.com/licy-yu/agent-os/api/controlplane/v1;v1b\x06proto3"

var (
	file_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_controlplane_v1_controlplane_proto_rawDescData
}

var file_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_controlplane_v1_controlplane_proto_goTypes = []any{
	(*HealthReply)(nil),                // 0: swarmos.controlplane.v1.HealthReply
	(*PageRequest)(nil),                // 1: swarmos.controlplane.v1.PageRequest
	(*Swarm)(nil),                      // 2: swarmos.controlplane.v1.Swarm
	(*CreateSwarmRequest)(nil),         // 3: swarmos.controlplane.v1.CreateSwarmRequest
	(*GetSwarmRequest)(nil),            // 4: swarmos.controlplane.v1.GetSwarmRequest
	(*ListSwarmsRequest)(nil),          // 5: swarmos.controlplane.v1.ListSwarmsRequest
	(*ListSwarmsReply)(nil),            // 6: swarmos.controlplane.v1.ListSwarmsReply
	(*AgentTemplate)(nil),              // 7: swarmos.controlplane.v1.AgentTemplate
	(*CreateAgentTemplateRequest)(nil), // 8: swarmos.controlplane.v1.CreateAgentTemplateRequest
	(*ListAgentTemplatesRequest)(nil),  // 9: swarmos.controlplane.v1.ListAgentTemplatesRequest
	(*ListAgentTemplatesReply)(nil),    // 10: swarmos.controlplane.v1.ListAgentTemplatesReply
	(*AgentInstance)(nil),              // 11: swarmos.controlplane.v1.AgentInstance
	(*RegisterAgentRequest)(nil),       // 12: swarmos.controlplane.v1.RegisterAgentRequest
	(*ListAgentsRequest)(nil),          // 13: swarmos.controlplane.v1.ListAgentsRequest
	(*ListAgentsReply)(nil),            // 14: swarmos.controlplane.v1.ListAgentsReply
	(*Task)(nil),                       // 15: swarmos.controlplane.v1.Task
	(*CreateTaskRequest)(nil),          // 16: swarmos.controlplane.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),             // 17: swarmos.controlplane.v1.GetTaskRequest
	(*ListTasksRequest)(nil),           // 18: swarmos.controlplane.v1.ListTasksRequest
	(*ListTasksReply)(nil),             // 19: swarmos.controlplane.v1.ListTasksReply
	nil,                                // 20: swarmos.controlplane.v1.AgentTemplate.SkillsEntry
	nil,                                // 21: swarmos.controlplane.v1.CreateAgentTemplateRequest.SkillsEntry
	(*structpb.Struct)(nil),            // 22: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 24: google.protobuf.Empty
}
var file_controlplane_v1_controlplane_proto_depIdxs = []int32{
	22, // 0: swarmos.controlplane.v1.Swarm.policy:type_name -> google.protobuf.Struct
	23, // 1: swarmos.controlplane.v1.Swarm.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: swarmos.controlplane.v1.Swarm.updated_at:type_name -> google.protobuf.Timestamp
	22, // 3: swarmos.controlplane.v1.CreateSwarmRequest.policy:type_name -> google.protobuf.Struct
	1,  // 4: swarmos.controlplane.v1.ListSwarmsRequest.page:type_name -> swarmos.controlplane.v1.PageRequest
	2,  // 5: swarmos.controlplane.v1.ListSwarmsReply.items:type_name -> swarmos.controlplane.v1.Swarm
	20, // 6: swarmos.controlplane.v1.AgentTemplate.skills:type_name -> swarmos.controlplane.v1.AgentTemplate.SkillsEntry
	23, // 7: swarmos.controlplane.v1.AgentTemplate.created_at:type_name -> google.protobuf.Timestamp
	23, // 8: swarmos.controlplane.v1.AgentTemplate.updated_at:type_name -> google.protobuf.Timestamp
	21, // 9: swarmos.controlplane.v1.CreateAgentTemplateRequest.skills:type_name -> swarmos.controlplane.v1.CreateAgentTemplateRequest.SkillsEntry
	1,  // 10: swarmos.controlplane.v1.ListAgentTemplatesRequest.page:type_name -> swarmos.controlplane.v1.PageRequest
	7,  // 11: swarmos.controlplane.v1.ListAgentTemplatesReply.items:type_name -> swarmos.controlplane.v1.AgentTemplate
	23, // 12: swarmos.controlplane.v1.AgentInstance.heartbeat_at:type_name -> google.protobuf.Timestamp
	23, // 13: swarmos.controlplane.v1.AgentInstance.created_at:type_name -> google.protobuf.Timestamp
	23, // 14: swarmos.controlplane.v1.AgentInstance.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 15: swarmos.controlplane.v1.ListAgentsRequest.page:type_name -> swarmos.controlplane.v1.PageRequest
	11, // 16: swarmos.controlplane.v1.ListAgentsReply.items:type_name -> swarmos.controlplane.v1.AgentInstance
	22, // 17: swarmos.controlplane.v1.Task.input:type_name -> google.protobuf.Struct
	22, // 18: swarmos.controlplane.v1.Task.requirements:type_name -> google.protobuf.Struct
	22, // 19: swarmos.controlplane.v1.Task.acceptance:type_name -> google.protobuf.Struct
	22, // 20: swarmos.controlplane.v1.Task.execution_policy:type_name -> google.protobuf.Struct
	23, // 21: swarmos.controlplane.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	23, // 22: swarmos.controlplane.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	22, // 23: swarmos.controlplane.v1.CreateTaskRequest.input:type_name -> google.protobuf.Struct
	22, // 24: swarmos.controlplane.v1.CreateTaskRequest.requirements:type_name -> google.protobuf.Struct
	22, // 25: swarmos.controlplane.v1.CreateTaskRequest.acceptance:type_name -> google.protobuf.Struct
	22, // 26: swarmos.controlplane.v1.CreateTaskRequest.execution_policy:type_name -> google.protobuf.Struct
	1,  // 27: swarmos.controlplane.v1.ListTasksRequest.page:type_name -> swarmos.controlplane.v1.PageRequest
	15, // 28: swarmos.controlplane.v1.ListTasksReply.items:type_name -> swarmos.controlplane.v1.Task
	24, // 29: swarmos.controlplane.v1.ControlPlane.Health:input_type -> google.protobuf.Empty
	3,  // 30: swarmos.controlplane.v1.ControlPlane.CreateSwarm:input_type -> swarmos.controlplane.v1.CreateSwarmRequest
	4,  // 31: swarmos.controlplane.v1.ControlPlane.GetSwarm:input_type -> swarmos.controlplane.v1.GetSwarmRequest
	5,  // 32: swarmos.controlplane.v1.ControlPlane.ListSwarms:input_type -> swarmos.controlplane.v1.ListSwarmsRequest
	8,  // 33: swarmos.controlplane.v1.ControlPlane.CreateAgentTemplate:input_type -> swarmos.controlplane.v1.CreateAgentTemplateRequest
	9,  // 34: swarmos.controlplane.v1.ControlPlane.ListAgentTemplates:input_type -> swarmos.controlplane.v1.ListAgentTemplatesRequest
	12, // 35: swarmos.controlplane.v1.ControlPlane.RegisterAgent:input_type -> swarmos.controlplane.v1.RegisterAgentRequest
	13, // 36: swarmos.controlplane.v1.ControlPlane.ListAgents:input_type -> swarmos.controlplane.v1.ListAgentsRequest
	16, // 37: swarmos.controlplane.v1.ControlPlane.CreateTask:input_type -> swarmos.controlplane.v1.CreateTaskRequest
	17, // 38: swarmos.controlplane.v1.ControlPlane.GetTask:input_type -> swarmos.controlplane.v1.GetTaskRequest
	18, // 39: swarmos.controlplane.v1.ControlPlane.ListTasks:input_type -> swarmos.controlplane.v1.ListTasksRequest
	0,  // 40: swarmos.controlplane.v1.ControlPlane.Health:output_type -> swarmos.controlplane.v1.HealthReply
	2,  // 41: swarmos.controlplane.v1.ControlPlane.CreateSwarm:output_type -> swarmos.controlplane.v1.Swarm
	2,  // 42: swarmos.controlplane.v1.ControlPlane.GetSwarm:output_type -> swarmos.controlplane.v1.Swarm
	6,  // 43: swarmos.controlplane.v1.ControlPlane.ListSwarms:output_type -> swarmos.controlplane.v1.ListSwarmsReply
	7,  // 44: swarmos.controlplane.v1.ControlPlane.CreateAgentTemplate:output_type -> swarmos.controlplane.v1.AgentTemplate
	10, // 45: swarmos.controlplane.v1.ControlPlane.ListAgentTemplates:output_type -> swarmos.controlplane.v1.ListAgentTemplatesReply
	11, // 46: swarmos.controlplane.v1.ControlPlane.RegisterAgent:output_type -> swarmos.controlplane.v1.AgentInstance
	14, // 47: swarmos.controlplane.v1.ControlPlane.ListAgents:output_type -> swarmos.controlplane.v1.ListAgentsReply
	15, // 48: swarmos.controlplane.v1.ControlPlane.CreateTask:output_type -> swarmos.controlplane.v1.Task
	15, // 49: swarmos.controlplane.v1.ControlPlane.GetTask:output_type -> swarmos.controlplane.v1.Task
	19, // 50: swarmos.controlplane.v1.ControlPlane.ListTasks:output_type -> swarmos.controlplane.v1.ListTasksReply
	40, // [40:51] is the sub-list for method output_type
	29, // [29:40] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_controlplane_v1_controlplane_proto_init() }
func file_controlplane_v1_controlplane_proto_init() {
	if File_controlplane_v1_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_v1_controlplane_proto = out.File
	file_controlplane_v1_controlplane_proto_goTypes = nil
	file_controlplane_v1_controlplane_proto_depIdxs = nil
}
